image:
- Visual Studio 2017
build: off

init:
  - git config --global core.autocrlf input

install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add versions
  - ps: scoop install sbt
  - SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g -Dsbt.supershell=never -Dfile.encoding=UTF8

environment:
  CI_SCALA_VERSION: 2.12.8

build_script:
  - sbt downloadIdea tests/compile

test_script:
  - sbt coreJVM/test
  - sbt ci-test

cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
  - '%USERPROFILE%\.coursier'
  - '%USERPROFILE%\scoop\cache'
  - scalafmt-intellij\idea
